import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { ClientLayout } from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Diablo 4 Item Comparison',
	description: 'Generated by create next app',
};

export const RootLayout = ({ children }) => (
	<html lang="en">
		<body className={inter.className}>
			<Providers>
				<ClientLayout>{children}</ClientLayout>
			</Providers>
		</body>
	</html>
);

export default RootLayout;
